apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ai-xray
type: Opaque
stringData:
  database-url: "postgresql://postgres:chestxpert123@postgres-svc.ai-xray.svc.cluster.local:5432/chestxpert"
